# A dictionary of supported funding model platforms
funding_platforms = {
    'github': ['enricoros'],  # Up to 4 GitHub Sponsors-enabled usernames e.g., ['user1', 'user2']
    'patreon': ['username'],  # A single Patreon username
    'open_collective': ['username'],  # A single Open Collective username
    'ko_fi': ['username'],  # A single Ko-fi username
    'tidelift': ['npm/babel'],  # A single Tidelift platform-name/package-name e.g., 'npm/babel'
    'community_bridge': ['project-name'],  # A single Community Bridge project-name e.g., 'cloud-foundry'
    'liberapay': ['username'],  # A single Liberapay username
    'issuehunt': ['username'],  # A single IssueHunt username
    'otechie': ['username'],  # A single Otechie username
    'lfx_crowdfunding': ['project-name'],  # A single LFX Crowdfunding project-name e.g., 'cloud-foundry'
    'custom': ['link1', 'link2']  # Up to 4 custom sponsorship URLs
}
